
server:
  port: 8080

spring:
  application:
    name: balancing

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: hello_route
          uri: lb://say-hello/greeting
          predicates:
            - Path=/hello
        - id: hi_route
          uri: lb://say-hello/hi
          predicates:
            - Path=/hi

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka}
    register-with-eureka: true